#ifndef ROOMDATA_H
#define ROOMDATA_H

#include <tonc_types.h>

/* Per-room map data for the ROOM page, generated by tools/gen_roomdata.py.
   Coordinates are world units (stage JSON units = player position units). */

typedef struct {
    s16 x, z;
    s16 dest;          /* stage id the loading zone warps to */
} MapDoor;

enum { MK_UNUSED, MK_OUTLET };  /* Chibi-Doors come from CL_CDOORS (chibi_link_pins.h) */

typedef struct {
    s16 x, z;
    u8 kind;           /* MK_* */
} MapMarker;

typedef struct {
    u8 stage;
    s16 min_x, max_x, min_z, max_z;
    u8 first_door, door_count;
    u8 first_marker, marker_count;
} MapRoom;

extern const MapDoor g_map_doors[];
extern const MapMarker g_map_markers[];
extern const MapRoom g_map_rooms[];
extern const int g_map_room_count;

#endif
