/*
 * Chibi-Robo! GBA Link - item pins for the GBA ROOM page.
 * Generated by tools/gen_roomdata.py from the apworld's locations.py - do not edit.
 *
 * Both sides expand CL_PINS(X): the GBA uses stage/x/z/name to draw a pin, the
 * GameCube uses addr/bit to report which of the current room's pins are
 * collected (CL_STATUS_PINS/_HI: bit k = the k-th pin of that room, in this
 * order). addr/bit are the location's pickup bit (bit N of the little-endian
 * u32 at addr, like client.py check_location), so a pin disappears as soon
 * as the check happens.
 *
 * kind: CL_PIN_ITEM, or CL_PIN_COIN for the coin_locations option's coins. Those
 * only exist when the seed has that option, which the randomizer tells the GC
 * code through cl_coin_pins. Without it the GC reports them as collected and
 * clears CL_FLAG_COIN_PINS, so the GBA leaves them off the map and the counts.
 *
 * X(stage, world x, world z, bitfield addr, bit, kind, name)
 */
#ifndef CHIBI_LINK_PINS_H
#define CHIBI_LINK_PINS_H

#define CL_PIN_ITEM 0
#define CL_PIN_COIN 1

#define CL_PIN_COUNT 214

#define CL_PINS(X) \
    X( 1,   -61,  -180, 0x8037DDCEu,  1, 0, "Mug Location") \
    X( 1,   119,  -182, 0x8037DDCEu,  2, 0, "Spoon Location") \
    X( 1,  -304,   245, 0x8037DDCEu,  3, 0, "Wastepaper by Foyer Door") \
    X( 1,   219,    24, 0x8037DDCEu,  4, 0, "Wastepaper under Counter") \
    X( 1,   142,   -86, 0x8037DDCEu,  5, 0, "Cookie Crumbs by Tao's Bowl") \
    X( 1,   163,  -163, 0x8037DDCEu,  6, 0, "Cookie Crumbs by Spoon") \
    X( 1,     6,    37, 0x8037DDCEu,  7, 0, "Cookie Crumbs on Kitchen Table") \
    X( 1,  -251,   -50, 0x8037DDCCu,  8, 0, "Cookie Crumbs next to Fridge on Counter") \
    X( 1,   329,   -33, 0x8037DDCCu,  9, 0, "Twig A") \
    X( 1,   352,   -48, 0x8037DDCCu, 10, 0, "Twig B") \
    X( 1,   359,   -36, 0x8037DDCCu, 11, 0, "Twig C") \
    X( 1,   314,  -182, 0x8037DDCCu, 12, 0, "Dog Tags Location") \
    X( 1,  -242,  -135, 0x8037DDCCu, 13, 0, "Bandage Location") \
    X( 1,   -42,   121, 0x8037DDCCu, 14, 0, "Frog Ring (Table)") \
    X( 1,  -244,   152, 0x8037DDCCu, 15, 0, "Pink Soda Can") \
    X( 1,  -258,   157, 0x8037DDCCu,  0, 0, "Purple Soda Can") \
    X( 1,   -71,    45, 0x8037DDCCu,  1, 0, "Table Candy Wrapper A") \
    X( 1,   -82,    56, 0x8037DDCCu,  2, 0, "Table Candy Wrapper B") \
    X( 1,   -24,   105, 0x8037DDCCu,  3, 0, "Table Candy Bag") \
    X( 1,   143,  -169, 0x8037DDCCu,  4, 0, "Cookie Box by Spoon A") \
    X( 1,   162,  -179, 0x8037DDCCu,  5, 0, "Cookie Box by Spoon B") \
    X( 1,    71,   240, 0x8037DDCCu,  6, 0, "Wastepaper on Shelf by Toaster") \
    X( 1,   245,   -23, 0x8037DDCCu,  7, 0, "Cookie Crumbs under Counter") \
    X( 1,   -81,  -152, 0x8037DDDAu,  4, 1, "High Cupboard 10M Coin") \
    X( 1,  -316,     0, 0x8037DDDAu,  5, 1, "10M Coin by Stove") \
    X( 1,    52,  -223, 0x8037DDDAu,  6, 1, "10M Coin by Sink") \
    X( 1,   212,  -195, 0x8037DDDAu,  7, 1, "10M behind Bottles") \
    X( 2,    93,   109, 0x8037DDDCu,  9, 0, "Free Rangers Photo") \
    X( 2,  -181,   293, 0x8037DDDCu, 10, 0, "Waterfall Frog Ring") \
    X( 2,  -184,  -124, 0x8037DDDCu, 11, 0, "Red Block") \
    X( 2,    66,    19, 0x8037DDDCu, 12, 0, "Wastepaper On Stairs") \
    X( 2,    95,    14, 0x8037DDDCu, 13, 0, "Candy Wrapper by Entrance") \
    X( 2,   121,    82, 0x8037DDDCu, 14, 0, "Candy Wrapper by Jenny Photo A") \
    X( 2,   137,    90, 0x8037DDDCu, 15, 0, "Candy Wrapper by Jenny Photo B") \
    X( 2,    25,   267, 0x8037DDDCu,  0, 0, "Soda Can on Shelf") \
    X( 2,  -207,   110, 0x8037DDDCu,  1, 0, "Candy Wrapper by Spaceship Shelf A") \
    X( 2,  -196,   120, 0x8037DDDCu,  2, 0, "Candy Wrapper by Spaceship Shelf B") \
    X( 2,  -212,   139, 0x8037DDDCu,  3, 0, "Candy Wrapper by Spaceship Shelf C") \
    X( 2,   -44,  -342, 0x8037DDDCu,  4, 0, "Candy Wrapper on Sofa A") \
    X( 2,   -57,  -345, 0x8037DDDCu,  5, 0, "Candy Wrapper on Sofa B") \
    X( 2,   185,  -218, 0x8037DDDCu,  6, 0, "Candy Wrapper on Floor by Door") \
    X( 2,  -159,  -350, 0x8037DDDCu,  7, 0, "Upstairs Wastepaper by Parents' Door") \
    X( 2,   -75,  -171, 0x8037DDE2u,  8, 0, "Upstairs Wastepaper by stairs") \
    X( 2,   -95,  -194, 0x8037DDE2u,  9, 0, "Upstairs Cookie Crumbs by stairs") \
    X( 2,  -153,  -338, 0x8037DDE2u, 10, 0, "Upstairs Candy Wrapper by Parents' Door") \
    X( 2,   192,   143, 0x8037DDE2u, 11, 0, "Upstairs Candy Wrapper by Jenny's Door A") \
    X( 2,   186,   154, 0x8037DDE2u, 12, 0, "Upstairs Candy Wrapper by Jenny's Door B") \
    X( 2,   -52,  -321, 0x8037DDE2u, 13, 0, "Candy Wrapper on Sofa C") \
    X( 2,  -192,   239, 0x8037DDE2u, 14, 0, "Candy Wrapper on Lower Shelf by Entrance") \
    X( 2,   181,  -100, 0x8037DDE2u, 15, 0, "Candy Wrapper on Stairs") \
    X( 2,   -89,    22, 0x8037DDE2u,  0, 0, "Upstairs Soda Can") \
    X( 2,    50,  -198, 0x8037DDE8u, 12, 1, "Top of Stairs 10M Coin") \
    X( 3,   108,   -37, 0x8037DDECu,  1, 0, "Giga Battery") \
    X( 3,    -4,   -92, 0x8037DDECu,  2, 0, "Giga Charger") \
    X( 3,  -108,   113, 0x8037DDECu,  3, 0, "Wine Bottle A") \
    X( 3,   -42,    80, 0x8037DDECu,  4, 0, "Wine Bottle B") \
    X( 3,   -89,   -52, 0x8037DDECu,  5, 0, "Wastepaper below Dresser") \
    X( 3,   -29,    76, 0x8037DDECu,  6, 0, "Wastepaper below Stairs") \
    X( 3,   -36,   109, 0x8037DDECu,  7, 0, "Wastepaper on Stairs") \
    X( 3,   -48,   -94, 0x8037DDF2u,  8, 0, "Wastepaper on Shelf") \
    X( 3,   -61,    92, 0x8037DDF2u,  9, 0, "Broken Bottle Bottom") \
    X( 3,  -101,   102, 0x8037DDF2u, 10, 0, "Broken Bottle Top") \
    X( 3,  -141,   -16, 0x8037DDF2u, 11, 0, "Gunpowder") \
    X( 3,   102,   136, 0x8037DDF2u, 12, 0, "Frog Ring") \
    X( 3,   -65,   -95, 0x8037DDF2u, 13, 0, "Purple Can") \
    X( 3,  -110,   -13, 0x8037DDF2u, 14, 0, "Cabinet Trash A") \
    X( 3,   -22,    86, 0x8037DDF2u, 15, 0, "Trash On Stairs") \
    X( 3,   -88,    29, 0x8037DDF8u,  4, 1, "Swing 10M Coin") \
    X( 3,     8,   120, 0x8037DDF8u,  5, 1, "Stairs 10M Coin A") \
    X( 3,   -92,   120, 0x8037DDF8u,  6, 1, "Stairs 10M Coin B") \
    X( 4,   197,    41, 0x8037DE02u,  9, 0, "AA Battery") \
    X( 4,   208,  -133, 0x8037DE02u, 10, 0, "D Battery") \
    X( 4,   215,     5, 0x8037DE02u, 11, 0, "C Battery") \
    X( 4,  -201,   105, 0x8037DE02u, 12, 0, "Wastepaper by Trashcan") \
    X( 4,   206,    80, 0x8037DE02u, 13, 0, "Wastepaper by Piano") \
    X( 4,    93,  -351, 0x8037DE02u, 14, 0, "Wastepaper under Dresser") \
    X( 4,   -74,  -324, 0x8037DE02u, 15, 0, "Wastepaper under Bed A") \
    X( 4,   -82,  -317, 0x8037DE02u,  0, 0, "Wastepaper under Bed B") \
    X( 4,   -10,  -320, 0x8037DE02u,  1, 0, "Wastepaper under Bed C") \
    X( 4,   -23,  -335, 0x8037DE02u,  2, 0, "Wastepaper under Bed D") \
    X( 4,    17,   198, 0x8037DE02u,  3, 0, "Wastepaper by Crayon Box") \
    X( 4,   225,  -336, 0x8037DE02u,  4, 0, "Red Shoe") \
    X( 4,   181,  -345, 0x8037DE02u,  5, 0, "Frog Ring") \
    X( 4,    33,   -99, 0x8037DE02u,  6, 0, "Squirter") \
    X( 4,   250,  -310, 0x8037DE02u,  7, 0, "Snorkel") \
    X( 4,   -90,  -314, 0x8037DE00u,  8, 0, "Cookie Crumbs under Bed A") \
    X( 4,   -19,  -346, 0x8037DE00u,  9, 0, "Cookie Crumbs under Bed B") \
    X( 4,     2,  -312, 0x8037DE00u, 10, 0, "Cookie Crumbs under Bed C") \
    X( 4,   -72,  -313, 0x8037DE00u, 11, 0, "Cookie Crumbs under Bed D") \
    X( 4,  -102,   158, 0x8037DE00u, 12, 0, "Cookie Crumbs by Chair") \
    X( 4,   -76,   196, 0x8037DE00u, 13, 0, "Cookie Crumbs on Desk A") \
    X( 4,   -84,   205, 0x8037DE00u, 14, 0, "Cookie Crumbs B") \
    X( 4,   -65,  -358, 0x8037DE00u, 15, 0, "Candy Wrapper below Bed A") \
    X( 4,     1,  -323, 0x8037DE00u,  0, 0, "Candy Wrapper below Bed B") \
    X( 4,   -12,  -309, 0x8037DE00u,  1, 0, "Candy Wrapper below Bed C") \
    X( 4,   -91,  -326, 0x8037DE00u,  2, 0, "Candy Wrapper on Bed A") \
    X( 4,    -3,  -326, 0x8037DE00u,  3, 0, "Candy Wrapper on Bed B") \
    X( 4,    28,   -62, 0x8037DE00u,  4, 0, "Candy Wrapper by TV") \
    X( 4,    34,   197, 0x8037DE00u,  5, 0, "Candy Wrapper by Crayon Box A") \
    X( 4,    73,   226, 0x8037DE00u,  6, 0, "Candy Wrapper by Crayon Box B") \
    X( 4,   -89,  -334, 0x8037DE00u,  7, 0, "Candy Bag under Bed") \
    X( 4,     0,  -339, 0x8037DE06u,  8, 0, "Candy Bag on Bed") \
    X( 4,   -16,  -328, 0x8037DE06u,  9, 0, "Cookie Box under Bed A") \
    X( 4,   -37,  -359, 0x8037DE06u, 10, 0, "Cookie Box under Bed B") \
    X( 4,  -102,   197, 0x8037DE06u, 11, 0, "Cookie Box on Desk") \
    X( 4,   -74,  -345, 0x8037DE06u, 12, 0, "Orange Can") \
    X( 4,   -81,  -360, 0x8037DE06u, 13, 0, "Purple Can") \
    X( 4,    15,   156, 0x8037DE06u, 14, 0, "Red Crayon") \
    X( 4,  -234,  -153, 0x8037DE06u, 15, 0, "Yellow Crayon") \
    X( 4,    -9,  -354, 0x8037DE06u,  0, 0, "Green Crayon") \
    X( 4,  -260,   -81, 0x8037DE06u,  1, 0, "Purple Crayon") \
    X( 4,   175,  -301, 0x8037DE06u,  2, 0, "Green Block") \
    X( 4,    -3,  -343, 0x8037DE06u,  3, 0, "Wastepaper under Bed E") \
    X( 4,   -85,  -133, 0x8037DE0Eu, 12, 1, "Stool 10M Coin") \
    X( 4,    21,  -218, 0x8037DE0Eu, 13, 1, "Bed Railing 10M Coin B") \
    X( 4,  -121,  -218, 0x8037DE0Eu, 14, 1, "Bed Railing 10M Coin A") \
    X( 4,  -197,  -347, 0x8037DE0Eu, 15, 1, "Slide 10M Coin") \
    X( 4,   259,    19, 0x8037DE0Eu,  0, 1, "10M Coin under Castle") \
    X( 6,  -311,   113, 0x8037DE20u,  9, 0, "Dinahs Teeth") \
    X( 6,    -4,   -56, 0x8037DE20u, 10, 0, "Ticket Stub") \
    X( 6,  -114,   272, 0x8037DE20u, 11, 0, "Passed Out Frog") \
    X( 6,    64,  -132, 0x8037DE20u, 12, 0, "Wastepaper by Bills B") \
    X( 6,    57,  -125, 0x8037DE20u, 13, 0, "Wastepaper by Bills A") \
    X( 6,   264,     1, 0x8037DE20u, 14, 0, "Wastepaper under Bed") \
    X( 6,   101,   239, 0x8037DE20u, 15, 0, "Wastepaper under Vanity") \
    X( 6,   109,   257, 0x8037DE20u,  0, 0, "Wastepaper on Vanity") \
    X( 6,   109,  -134, 0x8037DE20u,  1, 0, "Wastepaper on Bed") \
    X( 6,   181,   226, 0x8037DE20u,  2, 0, "Wastepaper by Dinahs Place A") \
    X( 6,   195,   225, 0x8037DE20u,  3, 0, "Wastepaper by Dinahs Place B") \
    X( 6,    83,  -132, 0x8037DE20u,  4, 0, "Cookie Crumbs on Toybox") \
    X( 6,    41,   264, 0x8037DE20u,  5, 0, "Vanity Candy Wrapper A") \
    X( 6,    29,   262, 0x8037DE20u,  6, 0, "Vanity Candy Wrapper B") \
    X( 6,   -54,  -151, 0x8037DE20u,  7, 0, "Shelf Candy Wrapper") \
    X( 6,    64,   265, 0x8037DE26u,  8, 0, "Vanity Candy Bag") \
    X( 6,   127,   206, 0x8037DE2Cu, 12, 1, "Vanity Stool 10M Coin") \
    X( 6,    33,   182, 0x8037DE2Cu, 13, 1, "10M Coin by Dinahs Place") \
    X( 6,    87,  -163, 0x8037DE2Cu, 14, 1, "10M Coin under Bed") \
    X( 6,    48,  -188, 0x8037DE2Cu, 15, 1, "10M Coin on Nightstand") \
    X( 6,   -77,  -131, 0x8037DE2Cu,  0, 1, "10M Coin on Shelf") \
    X( 7,  -231,   -62, 0x8037DE30u,  1, 0, "Frog Ring (Behind Window)") \
    X( 7,  -267,  -168, 0x8037DE30u,  2, 0, "Frog Ring (Corkboard)") \
    X( 7,  -253,    88, 0x8037DE30u,  3, 0, "Frog Ring (Shelf)") \
    X( 7,    85,   295, 0x8037DE30u,  4, 0, "Wastepaper by Trashbin B") \
    X( 7,   183,   300, 0x8037DE30u,  5, 0, "Candy Wrapper above Trashbin A") \
    X( 7,   210,   122, 0x8037DE30u,  7, 0, "Wastepaper by Trashbin A") \
    X( 7,    73,   -81, 0x8037DE36u,  8, 0, "Cupholder Wastepaper") \
    X( 7,   -49,     7, 0x8037DE36u,  9, 0, "Cookie Crumbs under Table") \
    X( 7,   223,  -225, 0x8037DE36u, 10, 0, "Cookie Crumbs by Record Player") \
    X( 7,    46,    43, 0x8037DE36u, 11, 0, "Toothbrush") \
    X( 7,   180,  -363, 0x8037DE36u, 12, 0, "Wastepaper by Door to Kitchen") \
    X( 7,  -195,  -308, 0x8037DE36u, 13, 0, "Fireplace Wastepaper A") \
    X( 7,  -183,  -306, 0x8037DE36u, 14, 0, "Fireplace Wastepaper B") \
    X( 7,    -5,  -188, 0x8037DE36u, 15, 0, "Wastepaper on Stack of Books") \
    X( 7,   156,   103, 0x8037DE36u,  0, 0, "Couch Wastepaper B") \
    X( 7,    91,    75, 0x8037DE36u,  1, 0, "Wastepaper by Toothbrush Spawn") \
    X( 7,    60,   -81, 0x8037DE36u,  2, 0, "Wastepaper below Cupholder") \
    X( 7,   158,    -4, 0x8037DE36u,  3, 0, "Couch Wastepaper A") \
    X( 7,   118,    12, 0x8037DE36u,  4, 0, "Cookie Crumbs under Couch") \
    X( 7,   155,   -29, 0x8037DE36u,  5, 0, "Cookie Crumbs on Couch") \
    X( 7,   278,   -76, 0x8037DE36u,  6, 0, "Twig A") \
    X( 7,   263,   -63, 0x8037DE36u,  7, 0, "Twig B") \
    X( 7,   254,   -95, 0x8037DE34u,  8, 0, "Twig C") \
    X( 7,   253,   307, 0x8037DE34u,  9, 0, "Wastepaper above Trashbin A") \
    X( 7,   246,   315, 0x8037DE34u, 10, 0, "Wastepaper above Trashbin B") \
    X( 7,   215,   352, 0x8037DE30u,  6, 0, "Candy Wrapper above Trashbin B") \
    X( 7,   -90,    85, 0x8037DE34u, 11, 0, "Candy Wrapper by Jenny A") \
    X( 7,   136,    94, 0x8037DE34u, 13, 0, "Couch Candy Wrapper") \
    X( 7,   -76,    89, 0x8037DE34u, 12, 0, "Candy Wrapper by Jenny B") \
    X( 7,   -44,  -168, 0x8037DE34u, 14, 0, "Candy Wrapper on Book Stack") \
    X( 7,    23,  -141, 0x8037DE34u,  0, 0, "Armchair Candy Wrapper B") \
    X( 7,    22,  -127, 0x8037DE34u, 15, 0, "Armchair Candy Wrapper A") \
    X( 7,    79,   -90, 0x8037DE34u,  1, 0, "Cupholder Candy Wrapper") \
    X( 7,   151,    53, 0x8037DE34u,  2, 0, "Couch Candy Bag") \
    X( 7,    -4,    49, 0x8037DE34u,  3, 0, "Table Cookie Box A") \
    X( 7,     1,    69, 0x8037DE34u,  4, 0, "Table Cookie Box B") \
    X( 7,   151,   -48, 0x8037DE34u,  5, 0, "Toy receipt on coach") \
    X( 7,   -48,    69, 0x8037DE3Cu,  4, 1, "Table 10M Coin") \
    X( 7,  -252,   -90, 0x8037DE3Cu,  5, 1, "Under Bookshelf 10M Coin") \
    X( 7,  -272,    45, 0x8037DE3Cu,  6, 1, "Under TV 10M Coin") \
    X( 7,  -227,  -121, 0x8037DE3Cu,  7, 1, "Bookshelf 10M Coin A") \
    X( 7,  -228,  -106, 0x8037DE42u,  8, 1, "Bookshelf 10M Coin B") \
    X( 7,    38,  -189, 0x8037DE42u,  9, 1, "Armchair 10M Coin") \
    X( 7,   156,   -29, 0x8037DE42u, 10, 1, "Under Couch 10M Coin") \
    X( 7,   175,     9, 0x8037DE42u, 11, 1, "Couch Backseat 10M Coin A") \
    X( 7,   175,    16, 0x8037DE42u, 12, 1, "Couch Backseat 10M Coin B") \
    X( 7,   175,     2, 0x8037DE42u, 13, 1, "Couch Backseat 10M Coin C") \
    X( 7,    69,   -92, 0x8037DE42u, 14, 1, "Cupholder 50M Coin") \
    X( 7,   256,   251, 0x8037DE42u, 15, 1, "Plant Shelf 50M A") \
    X( 7,   239,   266, 0x8037DE42u,  0, 1, "Plant Shelf 50M B") \
    X( 7,   215,   188, 0x8037DE42u,  1, 1, "Plant Leaf 50M Coin") \
    X( 7,    -7,  -161, 0x8037DE42u,  2, 1, "Armchair 50M Coin") \
    X( 7,   229,  -160, 0x8037DE42u,  3, 1, "Lamp 50M Coin") \
    X( 7,   -43,  -352, 0x8037DE42u,  4, 1, "50M Coin on top of Chibi House") \
    X( 7,   113,   113, 0x8037DE42u,  5, 1, "Couch 10M Coin (Below Left Armrest)") \
    X( 7,    -3,   364, 0x8037DE42u,  6, 1, "10M Coin behind Grandfather Clock Shelving A") \
    X( 7,     9,   364, 0x8037DE42u,  7, 1, "10M Coin behind Grandfather Clock Shelving B") \
    X( 7,    22,   364, 0x8037DE40u,  8, 1, "10M Coin behind Grandfather Clock Shelving C") \
    X( 9,   278,   -88, 0x8037DE56u,  1, 0, "Twig by Glass Door") \
    X( 9,   447,   196, 0x8037DE56u,  2, 0, "Twig by Fence") \
    X( 9,   624,  -638, 0x8037DE56u,  3, 0, "Twig under Tree") \
    X( 9,   346,  -408, 0x8037DE56u,  4, 0, "Twig under Awning") \
    X( 9,   628,  -465, 0x8037DE56u,  5, 0, "Frog Ring") \
    X( 9,   386,  -109, 0x8037DE56u,  6, 0, "White Block") \
    X(11,  -214,     0, 0x8037DE74u,  1, 0, "Frog Ring") \
    X(11,  -174,     1, 0x8037DE80u,  4, 1, "Middle Row 100M Coin A") \
    X(11,  -162,     1, 0x8037DE80u,  5, 1, "Middle Row 100M Coin B") \
    X(11,  -150,     1, 0x8037DE80u,  6, 1, "Middle Row 100M Coin C") \
    X(11,  -198,     1, 0x8037DE80u,  7, 1, "Middle Row 10M Coin B") \
    X(11,  -186,     1, 0x8037DE86u,  8, 1, "Middle Row 10M Coin C") \
    X(11,  -300,     1, 0x8037DE86u,  9, 1, "Top Row 100M Coin") \
    X(11,  -276,     1, 0x8037DE86u, 10, 1, "Top Row 10M Coin A") \
    X(11,  -288,     1, 0x8037DE86u, 11, 1, "Top Row 10M Coin B") \
    X(22,   -12,    50, 0x8037DF30u,  9, 0, "Frog Ring") \
    X(22,    12,    50, 0x8037DF30u, 10, 0, "Left Leg") \

/* Chibi-Doors: X(stage, world x, world z, script flag set when opened).
   flag(N) = bit N%32 of the big-endian u32 at 0x8036781C + (N/32)*4.
   CL_STATUS_CDOORS bit k = the current room's k-th door (in this order) is open. */
#define CL_CDOOR_COUNT 60

#define CL_CDOORS(X) \
    X( 1,  -103,   267,  711) /* house_r_chibi_h_door_1 27 */ \
    X( 1,   316,   266,  712) /* house_r_chibi_h_door_1 28 */ \
    X( 1,  -221,   149,  713) /* house_r_chibi_h_door_1 29 */ \
    X( 1,   216,    46,  714) /* house_r_chibi_h_door_1 30 */ \
    X( 1,   250,   -83,  715) /* house_r_chibi_h_door_1 31 */ \
    X( 1,    99,   267,  716) /* house_r_chibi_h_door_1 32 */ \
    X( 1,  -275,  -112,  717) /* house_r_chibi_h_door_1 33 */ \
    X( 1,   193,   136,  718) /* house_r_chibi_h_door_1 34 */ \
    X( 1,   195,  -200,  719) /* house_r_chibi_h_door_1 35 */ \
    X( 2,   229,    89,  731) /* house_r_chibi_h_door_1 111 */ \
    X( 2,   -62,  -369,  732) /* house_r_chibi_h_door_1 112 */ \
    X( 2,   251,  -202,  733) /* house_r_chibi_h_door_1 113 */ \
    X( 2,  -226,    74,  735) /* house_r_chibi_h_door_1 114 */ \
    X( 2,  -213,  -168,  736) /* house_r_chibi_h_door_1 115 */ \
    X( 2,    -9,  -379,  737) /* house_r_chibi_h_door_1 116 */ \
    X( 2,   225,  -345,  738) /* house_r_chibi_h_door_1 117 */ \
    X( 2,   228,    73,  740) /* house_r_chibi_h_door_1 118 */ \
    X( 2,     1,   359,  742) /* house_r_chibi_h_door_1 119 */ \
    X( 2,   225,   295,  743) /* house_r_chibi_h_door_1 120 */ \
    X( 2,  -233,   112,  745) /* house_r_chibi_h_door_1 121 */ \
    X( 3,   120,   176,  748) /* house_r_chibi_h_door_1 17 */ \
    X( 3,  -134,   -53,  750) /* house_r_chibi_h_door_1 18 */ \
    X( 3,   134,    60,  751) /* house_r_chibi_h_door_1 19 */ \
    X( 3,  -179,   -60,  753) /* house_r_chibi_h_door_1 20 */ \
    X( 4,  -254,   -83,  756) /* house_r_chibi_h_door_1 24 */ \
    X( 4,   244,     0,  757) /* house_r_chibi_h_door_1 25 */ \
    X( 4,  -102,  -360,  758) /* house_r_chibi_h_door_1 26 */ \
    X( 4,   275,  -344,  759) /* house_r_chibi_h_door_1 27 */ \
    X( 4,    95,  -366,  761) /* house_r_chibi_h_door_1 28 */ \
    X( 4,  -275,  -254,  762) /* house_r_chibi_h_door_1 29 */ \
    X( 4,  -182,  -375,  764) /* house_r_chibi_h_door_1 30 */ \
    X( 6,   302,   -80,  766) /* house_r_chibi_h_door_1 6 */ \
    X( 6,   302,   -40,  767) /* house_r_chibi_h_door_1 7 */ \
    X( 6,   302,     0,  768) /* house_r_chibi_h_door_1 8 */ \
    X( 6,   302,    40,  769) /* house_r_chibi_h_door_1 9 */ \
    X( 6,   319,  -163,  770) /* house_r_chibi_h_door_1 10 */ \
    X( 6,  -339,  -173,  780) /* house_r_chibi_h_door_1 11 */ \
    X( 6,  -303,   -80,  781) /* house_r_chibi_h_door_1 12 */ \
    X( 6,  -303,   -40,  782) /* house_r_chibi_h_door_1 13 */ \
    X( 6,  -303,     0,  783) /* house_r_chibi_h_door_1 14 */ \
    X( 6,  -303,    40,  784) /* house_r_chibi_h_door_1 15 */ \
    X( 6,   191,   289,  785) /* house_r_chibi_h_door_1 16 */ \
    X( 6,   208,  -197,  786) /* house_r_chibi_h_door_1 17 */ \
    X( 7,  -275,  -164,  701) /* house_r_chibi_h_door_1 92 */ \
    X( 7,  -103,  -374,  702) /* house_r_chibi_h_door_1 93 */ \
    X( 7,  -208,   365,  703) /* house_r_chibi_h_door_1 94 */ \
    X( 7,  -172,  -345,  704) /* house_r_chibi_h_door_1 95 */ \
    X( 7,  -275,   146,  705) /* house_r_chibi_h_door_1 96 */ \
    X( 7,   270,   257,  706) /* house_r_chibi_h_door_1 97 */ \
    X( 7,   241,  -333,  708) /* house_r_chibi_h_door_1 98 */ \
    X( 7,    92,   342,  709) /* house_r_chibi_h_door_1 99 */ \
    X( 7,   165,    79,  710) /* house_r_chibi_h_door_1 100 */ \
    X( 9,   282,   239,  787) /* house_r_chibi_h_door_1 16 */ \
    X( 9,   283,  -630,  788) /* house_r_chibi_h_door_1 17 */ \
    X( 9,   637,  -585,  789) /* house_r_chibi_h_door_1 18 */ \
    X( 9,   275,   180,  790) /* house_r_chibi_h_door_1 19 */ \
    X( 9,   275,  -291,  791) /* house_r_chibi_h_door_1 20 */ \
    X( 9,   274,  -242,  792) /* house_r_chibi_h_door_1 21 */ \
    X( 9,   617,  -530,  795) /* house_r_chibi_h_door_1 22 */ \
    X( 9,   585,  -609,  796) /* house_r_chibi_h_door_1 23 */ \

#endif
