#!/usr/bin/env python3
"""
Converts the Chibi-Robo art in gba/art/ into GBA sprite data:

    py tools/gen_sprites.py          (build.bat runs this before make)

gba/art/chibi_head.png   16x16 title-bar head -> gba/source/chibi_head.c

gba/art/chibi_0..3.webp  side-on walk cycle (facing left) -> gba/source/chibi_walk.c
    scaled to 32x32, bottom-aligned, and mapped to the palette greys.

Output is 4bpp tile data in 1D OBJ mapping order, OBJ palette bank 0.

GBA doesn't like normal files and need to make sure it is corret format 

Based on: https://github.com/BobDev94/Pic2Pix
"""
import os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ART = os.path.join(HERE, "..", "gba", "art")
SRC = os.path.join(HERE, "..", "gba", "source")

# OBJ palette bank 0 as set in gba/source/gfx.c palettes_init() - keep in sync.
OBJ_PALETTE = {
    1: (26, 28, 44),     # outline
    2: (255, 255, 255),  # white
    3: (176, 184, 208),  # silver
    4: (32, 40, 72),     # eye navy
    5: (248, 136, 40),   # orange
    6: (255, 232, 96),   # yellow
    7: (120, 200, 255),  # light blue
    8: (120, 128, 156),  # mid grey
    9: (216, 222, 236),  # light grey
    11: (72, 208, 88),   # green
    13: (232, 48, 48),   # red
    14: (255, 170, 190), # pink
}

WALK_FRAMES = ["chibi_0.webp", "chibi_1.webp", "chibi_2.webp", "chibi_3.webp"]
WALK_SIZE = 32


def nearest_index(r, g, b):
    return min(OBJ_PALETTE, key=lambda i: sum((c - p) ** 2 for c, p in zip((r, g, b), OBJ_PALETTE[i])))


def grey_index(r, g, b):
    v = (r + g + b) / 3
    return 1 if v < 70 else 8 if v < 140 else 3 if v < 200 else 9 if v < 238 else 2


def pack_tiles(pix, size):
    """size x size palette indices -> 4bpp words, 1D mapping (tiles row by row)."""
    words = []
    for ty in range(size // 8):
        for tx in range(size // 8):
            for y in range(8):
                w = 0
                for x in range(8):
                    w |= pix[ty * 8 + y][tx * 8 + x] << (x * 4)
                words.append(w)
    return words


def write_c(path, name, words, comment, source):
    with open(path, "w", newline="\n") as fh:
        fh.write("/* Generated by tools/gen_sprites.py from %s - do not edit. */\n" % source)
        fh.write('#include "gfx.h"\n\n')
        fh.write("/* %s */\n" % comment)
        fh.write("const unsigned int %s[%d] = {\n" % (name, len(words)))
        for i in range(0, len(words), 8):
            fh.write("    " + ", ".join("0x%08X" % w for w in words[i:i + 8]) + ",\n")
        fh.write("};\n")
    print("wrote %s (%d bytes)" % (os.path.relpath(path, os.path.join(HERE, "..")), len(words) * 4))


def head():
    im = Image.open(os.path.join(ART, "chibi_head.png")).convert("RGBA")
    if im.size != (16, 16):
        raise SystemExit("gba/art/chibi_head.png must be 16x16 (is %dx%d)" % im.size)
    pix = [[0] * 16 for _ in range(16)]
    for y in range(16):
        for x in range(16):
            r, g, b, a = im.getpixel((x, y))
            if a >= 128:
                pix[y][x] = nearest_index(r, g, b)
    write_c(os.path.join(SRC, "chibi_head.c"), "chibi_head_tiles", pack_tiles(pix, 16),
            "16x16 title-bar Chibi-Robo head (4 tiles, 4bpp, 1D order), OBJ palette bank 0",
            "gba/art/chibi_head.png")


def walk():
    frames = [Image.open(os.path.join(ART, f)).convert("RGBA") for f in WALK_FRAMES]
    boxes = [f.getchannel("A").point(lambda a: 255 if a >= 96 else 0).getbbox() for f in frames]
    box = (min(b[0] for b in boxes), min(b[1] for b in boxes), max(b[2] for b in boxes), max(b[3] for b in boxes))
    words = []
    for fr in frames:
        f = fr.crop(box)
        scale = min(WALK_SIZE / f.width, WALK_SIZE / f.height)
        nw, nh = max(1, round(f.width * scale)), max(1, round(f.height * scale))
        f = f.resize((nw, nh), Image.LANCZOS)
        ox, oy = (WALK_SIZE - nw) // 2, WALK_SIZE - nh
        pix = [[0] * WALK_SIZE for _ in range(WALK_SIZE)]
        for y in range(nh):
            for x in range(nw):
                r, g, b, a = f.getpixel((x, y))
                if a >= 110:
                    pix[oy + y][ox + x] = grey_index(r, g, b)
        words += pack_tiles(pix, WALK_SIZE)
    write_c(os.path.join(SRC, "chibi_walk.c"), "chibi_walk_tiles", words,
            "%d frames of 32x32 (16 tiles, 4bpp, 1D order), OBJ palette bank 0" % len(WALK_FRAMES),
            "gba/art/chibi_0..3.webp")


if __name__ == "__main__":
    head()
    walk()
